services:
  - type: web
    name: streamlit-04
    plan: free
    env: python
    runtime: python
    buildCommand: |
      # Backend dependencies
      cd backend
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt

      # Frontend build
      cd ../frontend/news-app
      npm install --legacy-peer-deps
      npm run build
    startCommand: |
      cd backend
      uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: SQLITE_PATH
        value: /tmp/news.db
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OPENAI_API_KEY
        sync: false

