services:
  - type: web
    name: streamlit-04
    runtime: python
    env: python
    buildCommand: |
      cd backend
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 18