services:
  - type: web
    name: streamlit-04
    plan: free
    env: python
    runtime: python
    buildCommand: |
      # Backend dependencies
      cd backend
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      
      # Frontend build
      cd ../frontend/news-app
      npm install --legacy-peer-deps
      npm run build
      
    startCommand: |
      cd backend
      gunicorn wsgi:application --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker
      
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: SQLITE_PATH
        value: /var/data/news.db
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: OPENAI_API_KEY
        sync: false



